[project]
name = "project-rh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling>=2.51.0",
    "langchain>=0.3.27",
    "langchain-community>=0.3.29",
    "langchain-google-genai>=2.1.10",
    "llama-index>=0.12.52",
    "matplotlib>=3.10.6",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "pdf2image>=1.17.0",
    "pdfminer-six>=20250506",
    "pi-heif>=1.1.0",
    "pypdf>=5.9.0",
    "pytesseract>=0.3.13",
    "seaborn>=0.13.2",
    "unstructured-inference>=1.0.5",
    "unstructured[all,all-docs]>=0.18.14",
]
